name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Source/Mocha.sln

    - name: Build
      run: dotnet publish --output "/tmp/build" -c Release -r linux-x64 Source/Mocha.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal Source/Mocha.sln

    - name: Build Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_PUBLIC }}
          description: "Linux: build success"
    
    - name: Build Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_PUBLIC }}
          description: "Linux: build failed"
          text: "https://tenor.com/view/conductor-we-have-a-problem-cat-cute-funny-gif-17168115721186324165"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: /tmp/build
