name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore source/mocha.sln

    - name: Build
      run: dotnet build --no-restore source/mocha.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal source/mocha.sln
