name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore source/mocha.sln

    - name: Build
      run: dotnet publish --output "C:\temp\build" -c Release -r win-x64 source/mocha.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal source/mocha.sln

    - name: Build Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_PUBLIC }}
          description: Build finished.
    
    - name: Build Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_PUBLIC }}
          description: Build failed!

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: C:\temp\build
        
    - name: Upload to steam
      uses: game-ci/steam-deploy@v3
      with:
        username: ${{ secrets.STEAM_USERNAME }}          
        configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
        appId: 2280950
        buildDescription: ${{ github.sha }}
        rootPath: build
        depot1Path: StandaloneWindows64
        releaseBranch: prerelease
