name: Discord Webhook

on:
  push:
    branches:
      - '*'
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: Retr0-01/better-discord-notification@main
        with:
          webhook-url: ${{ secrets.CI_DISCORD_WEBHOOK_PUBLIC }}
          embed-color: '921102'
          footer-icon: ${{ secrets.CI_DISCORD_WEBHOOK_ICON }}
